<?xml version="1.0"?>
<package format="3">
  <name>dronet_perception</name>
  <version>0.0.1</version>
  <description>DroNet steering + collision probability inference for AURORA-ADAS</description>

  <maintainer email="emmanuel@example.com">Emmanuel</maintainer>
  <license>MIT</license>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>OpenCV</depend>
  <depend>geometry_msgs</depend>

  <build_depend>ament_cmake</build_depend>
  <exec_depend>ament_cmake</exec_depend>
</package>
