<?xml version="1.0"?>
<package format="3">
  <name>world_model_node</name>
  <version>0.0.1</version>
  <description>World model node for AURORA-ADAS</description>

  <maintainer email="emmanuel@example.com">Emmanuel</maintainer>
  <license>MIT</license>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>cv_bridge</depend>

</package>
