<?xml version="1.0"?>
<package format="3">
  <name>auroadas</name>
  <version>0.0.1</version>
  <description>AUROADAS: Real-time multi-sensor localization and perception stack</description>
  <maintainer email="you@example.com">Emmanuel Musvaire</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>Eigen3</depend>
  <depend>opencv</depend>

</package>
