<?xml version="1.0"?>
<package format="3">
  <name>local_mapper</name>
  <version>0.0.1</version>
  <description>Local occupancy grid mapper for AUROUAV-ADAS</description>

  <maintainer email="emmanuel@example.com">Emmanuel</maintainer>
  <license>MIT</license>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

</package>
